### ISSUE TITLE
apk has incorrect extra filed in the entry

### ISSUE THREAD

**Issue by oleg-cherednik** [oleg-cherednik/zip4jvm#67]
`apk` file keeps file content in the extra field section. But this section has not correct format for extra field. According this, decompose and view has a problem.

**Comment by pmqs** [comment]
Do you have a sample apk file that illustrates the issue?

**Comment by oleg-cherednik** [comment]
@pmqs yes, I do. I think this is any apk file with resources. E.g. I have tested on this one: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=4299166&key=9d0c4877d79538ba4f45287479a3b11dd8c5e733&forcebaseapk=true

**Comment by oleg-cherednik** [comment]
Will be inlcuded in **v1.9**

**Comment by pmqs** [comment]
> 

Thanks - quite a big file.

The only thing non-standard I can see is null padding bytes where the extra fields should. See below for an example from the link you posted.

```
00029D2 0000004 50 4B 03 04 LOCAL HEADER #4       04034B50
00029D6 0000001 00          Extract Zip Spec      00 '0.0'
00029D7 0000001 00          Extract OS            00 'MS-DOS'
00029D8 0000002 00 00       General Purpose Flag  0000
00029DA 0000002 00 00       Compression Method    0000 'Stored'
00029DC 0000004 21 08 21 02 Last Mod Time         02210821 'Thu Jan  1 01:01:02 1981'
00029E0 0000004 E7 A5 1B 33 CRC                   331BA5E7
00029E4 0000004 06 00 00 00 Compressed Length     00000006
00029E8 0000004 06 00 00 00 Uncompressed Length   00000006
00029EC 0000002 2B 00       Filename Length       002B
00029EE 0000002 01 00       Extra Length          0001
00029F0 000002B 4D 45 54 41 Filename              'META-INF/androidx.activity_activity.
                2D 49 4E 46                       version'
                2F 61 6E 64
                72 6F 69 64
                78 2E 61 63
                74 69 76 69
                74 79 5F 61
                63 74 69 76
                69 74 79 2E
                76 65 72 73
                69 6F 6E
0002A1B 0000001 00          Null Padding in Extra   <=======================
0002A1C 0000006 31 2E 32 2E PAYLOAD               1.2.4.
                34 0A
```

**Comment by oleg-cherednik** [comment]
`0002A1B`  for `LocalFileHeader` here should be a `extra field length` (see [4.3.7](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT)) and each record in this section should have format containeng at least `archive extra data signature (4 bytes)` and `extra field length (4 bytes)`  (see [4.3.11](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT)). So in the `LocalFileHeader` we should have at least `8 bytes`, but we have only `1 byte`. This is not up to standard. I have fixed this.

**Comment by oleg-cherednik** [comment]
I think you can be right about data alignemnt, because `apk` is for Android and file should be start at the special postion in memory.

My application just work with zip file and should decompose it correctly. Thank you for mention about data alignment.

**Comment by oleg-cherednik** [comment]
https://github.com/Ne-Lexa/php-zip/releases here you can find what is `0xD935`
